#! /usr/bin/env bash

declare interne="Programmation"
echo $interne

if [[ -n "$publique" ]]; then
    if [[ -z "$publique" ]];then
        echo "empty variable" >&2
    else
        echo $publique
    
    fi
else
    echo "La variable n'existe pas!" 2>&1
fi 
